# Generated by Django 3.1.1 on 2020-10-23 06:29

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201023_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, help_text='例:1996-05-31', null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'そのEメールアドレスはすでに使用されています'}, max_length=254, unique=True, verbose_name='Eメール'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(help_text='男性は170cm未満のかた限定です。', verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='150文字以下。文字と数字と @/./+/-/_ のみ。', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='ユーザ名'),
        ),
    ]
